version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: hyu_hsj_valorbank
    environment:
      MYSQL_ROOT_PASSWORD: hsj
      MYSQL_DATABASE: valorbankdb
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped